### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by Z-zachary** [bronemos/view-fusion#5]

**Comment by Z-zachary** [comment]
Can you publish the inference code?

**Comment by bronemos** [comment]
Hi, the inference code is available in `inference.py`. Unfortunately, this is still a working version of it (i.e. no comments, and there might be smaller bugs) as we're currently working on moving the project into another framework. Hopefully once that's done in the coming months, we will be able to update this repository with a cleaner version of the inference script.

However, if you have good python / pytorch understanding, running the inference script should be possible without too many issues.

**Comment by bronemos** [comment]
Hi, 

I've got back to cleaning up the repository and simplifying some of the functionality. In case it's still relevant, some inference functionalities are now available to reproduce figures in the paper and README, the instructions can be found in README of the repo.
